name: Simpleworkflow

on: push

jobs: 
  Firstbuild:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: printworld
        run : |
          echo "Hellow World!"
          echo "list of file and folder in current directory"
          ls -ltra
          echo "completed run for Printworld"

  Secondbuild:
    runs-on: windows-latest
    steps:
      - name: Printcmd
        run: |
          echo "CMD"
          echo "%homepath%"
          dir
          echo "completed the secondbuild"
          
  
  
  
