name: Simpleworkflow

on: push

jobs: 
  Firstbuild:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: printworld
        run : echo "Hellow World!"
        run : echo "completed running simple work flow"
  
  
  
  
